apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: puma-k8s-test
    process: web
  name: puma-k8s-test-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: puma-k8s-test
      process: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: puma-k8s-test
        process: web
    spec:
      containers:
      - env:
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 1
        image: puma-k8s-test:v1
        imagePullPolicy: IfNotPresent
        name: puma-k8s-test-web
        command: ["bundle", "exec", "puma", "-p", "3000", "--threads", "4:6", "--workers", "8", "--preload", "--silent"]
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
